# Local development only. Not for use in Production.
version: "3.9"

services:

  muya-django:
    build:
      context: .
      dockerfile: docker/django-dev/Dockerfile
      args:
        - CONTEXT_GIT_COMMITISH=${CONTEXT_GIT_COMMITISH:-HEAD}
    image: muya-django:latest
    ports:
      - ${MUYA_HOST_PORT:-34830}:8000
    env_file:
      - config/muya-django.env
      - ${MUYA_ENV_OVERRIDE_FILE:-config/empty.env}
    environment:
      - MUYA_DEVSERVER=${MUYA_DEVSERVER:-true}
      - COLLATEX_URL=${COLLATEX_URL:-http://muya-collation:7369/}
    volumes:
      - .:/opt/muya_wce
    depends_on:
      - muya-collation
      - muya-broker
      - muya-db
      - muya-celery

  muya-collation:
    build:
      context: .
      dockerfile: docker/collation-dev/Dockerfile
    image: muya-collation:latest
    ports:
      - ${COLLATION_HOST_PORT:-34866}:7369

  muya-celery:
    build:
      context: .
      dockerfile: docker/django-dev/Dockerfile
      args:
        - CONTEXT_GIT_COMMITISH=${CONTEXT_GIT_COMMITISH:-HEAD}
    image: muya-celery:latest
    command: run-celery
    env_file:
      - config/muya-django.env
      - ${MUYA_ENV_OVERRIDE_FILE:-config/empty.env}
    environment:
      - MUYA_DEVSERVER=${MUYA_DEVSERVER:-true}
    volumes:
      - .:/opt/muya_wce
    depends_on:
      - muya-broker
      - muya-db

  muya-broker:
    image: "rabbitmq:3.9-management-alpine"
    restart: always
    ports:
      - ${MUYA_BROKER_HOST_PORT:-34873}:5672
      - ${MUYA_BROKER_MANAGE_HOST_PORT:-34874}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-muya}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD:-muya}
    volumes:
      - muya-queue:/var/lib/rabbitmq

  muya-db:
    build:
      context: .
      dockerfile: docker/db-dev/Dockerfile
    image: muya-db:latest
    restart: always
    ports:
      - ${MUYA_DB_HOST_PORT:-34833}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-postgres}
      MUYA_PASSWORD: ${MUYA_DB_PASSWORD:-muya}
    volumes:
      - muya-db:/var/lib/postgresql/data

volumes:
  muya-queue:
  muya-db:

